#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

runcmd:
  - echo "Fichier cloud-init initialisé pour l'architecture Azure !" > /var/www/html/index.html
